import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Navigation
    navDashboard: 'Dashboard',
    navSuperAdmin: 'Admin',
    navCharts: 'Charts',
    navSearch: 'Search',
    navReports: 'Reports',
    navUpload: 'Upload',
    navUsers: 'Users',
    navActivityLogins: 'Logins',
    navVoiceRecord: 'Voice',
    navTextSimplify: 'Simplify',
    navTrendAnalysis: 'Trends',
    navNotifications: 'Notifications',
    navSettings: 'Settings',
    navAdminTools: 'Admin Tools',
    navProfileSettings: 'Profile Settings',
    navChangePassword: 'Change Password',
    navManageEvents: 'Manage Events',
    navUploadProfileImage: 'Upload Profile Image',
    navNoEmail: 'No email',
    navRecentAppEvents: 'Recent app mail and push events',
    navMarkAllRead: 'Mark all read',
    navMarking: 'Marking...',
    navViewAll: 'View all',
    navNoRecentNotifications: 'No recent notifications yet.',
    navOpenNotificationCenterForDetails: 'Open the notification center for details.',
    navLogoutConfirmTitle: 'Sign out of your account?',
    navLogoutConfirm: 'Are you sure you want to logout?',
    navLastUpdated: 'Last updated',
    navLastUpdatedJustNow: 'Last updated just now',
    navLastUpdatedRecently: 'Last updated recently',
    navLogout: 'Logout',

    // Login
    loginSubtitle: 'Secure sign in for analytics, reports, and governance workflows',
    loginUsername: 'Username',
    loginUsernamePlaceholder: 'Enter your username',
    loginUsernameRequired: 'Username is required',
    loginPassword: 'Password',
    loginPasswordPlaceholder: 'Enter your password',
    loginPasswordRequired: 'Password is required',
    loginHidePassword: 'Hide password',
    loginShowPassword: 'Show password',
    loginSigningIn: 'Signing in...',
    loginSignInSecurely: 'Sign In Securely',
    loginForgotPassword: 'Forgot Password',
    loginHint: 'Use your assigned credentials. Account actions are monitored for security.',
    loginSupport: 'Contact your administrator for access',

    // Auth Flow (Change/Reset/Forgot Password)
    authChangePasswordTitle: 'Change Password',
    authMandatoryChangeSubtitle: 'Welcome, {username}! You are using a temporary password. Please change it before continuing.',
    authOptionalChangeSubtitle: 'Welcome back, {username}! Update your password.',
    authForcedChangeBannerTitle: 'Temporary password detected',
    authForcedChangeBannerBody: 'This account was issued a temporary password. For security, you must set a new password before you can continue using the application.',
    authCurrentPassword: 'Current Password',
    authCurrentPasswordPlaceholder: 'Enter your current password',
    authCurrentPasswordRequired: 'Current password is required',
    authHideCurrentPassword: 'Hide current password',
    authShowCurrentPassword: 'Show current password',
    authNewPassword: 'New Password',
    authNewPasswordPlaceholder: 'Create a strong password',
    authNewPasswordRequired: 'New password is required',
    authRuleMinLength: 'Minimum 8 characters',
    authRuleUppercase: '1 uppercase letter required',
    authRuleLowercase: '1 lowercase letter required',
    authRuleNumber: '1 number required',
    authRuleSpecial: '1 special character required',
    authHideNewPassword: 'Hide new password',
    authShowNewPassword: 'Show new password',
    authChecklistLength: '8+ characters',
    authChecklistCase: 'Lower + Upper case',
    authChecklistNumber: 'Number (0-9)',
    authChecklistSpecial: 'Special character',
    authPasswordStrengthWeak: 'Password strength: weak',
    authPasswordStrengthMedium: 'Password strength: medium',
    authPasswordStrengthStrong: 'Password strength: strong',
    authConfirmNewPassword: 'Confirm New Password',
    authConfirmNewPasswordPlaceholder: 'Repeat new password',
    authConfirmPasswordRequired: 'Please confirm password',
    authPasswordsDoNotMatch: 'Passwords do not match',
    authHideConfirmPassword: 'Hide confirm password',
    authShowConfirmPassword: 'Show confirm password',
    authChangeHint: 'Choose a unique password and avoid reusing credentials from other systems.',
    authChangingPassword: 'Changing Password...',
    authChangeAndContinue: 'Change Password & Continue',
    authBackToApplication: 'Back to Application',
    authBackToLogin: 'Back to Login',
    authPasswordMustMeetRequirements: 'Password must meet all requirements above',
    authNewPasswordDifferent: 'New password must be different from your current password.',
    authPasswordUpdated: 'Password updated successfully. Your account is now secured.',
    authChangePasswordFailed: 'Password change failed. Please verify your current password and retry.',
    authResetSuccess: 'Password reset complete. You can now sign in with your new password.',
    authResetFailed: 'Password reset failed. Please request a new reset link.',
    authInvalidResetTitle: 'Invalid Reset Link',
    authInvalidResetSubtitle: 'This reset link is missing or malformed. Request a new password reset link.',
    authRequestNewLink: 'Request New Link',
    authResetTitle: 'Reset Password',
    authResetSubtitle: 'Create your new password.',
    authResetHint: 'Use a password you have not used before. Keep it private and store it securely.',
    authResetting: 'Resetting...',
    authResetButton: 'Reset Password',
    authResetFooter: 'This link expires in 1 hour. Password must meet requirements above.',
    authForgotTitle: 'Forgot Password',
    authForgotSubtitle: 'Enter your registered email to receive a secure password reset link.',
    authEmailAddress: 'Email Address',
    authEmailPlaceholder: 'your.email@example.com',
    authEmailRequired: 'Email is required',
    authEmailInvalid: 'Enter a valid email address',
    authSendingResetLink: 'Sending Reset Link...',
    authSendResetLink: 'Send Reset Link',
    authForgotHint: 'If the email exists, a reset link will be sent. For security, we do not reveal account status.',
    authForgotSupport: 'Need help? Contact your administrator if you no longer have access to your inbox.',
    authForgotRequestReceived: 'Request received. If this email is registered, reset instructions are on the way.',
    authForgotRequestFailed: 'We could not process your request right now. Please try again.',

    // User Management
    umAdminRequired: 'Admin access is required for user management.',
    umLoadUsersFailed: 'Unable to load users at the moment.',
    umUserCreated: 'User "{username}" created successfully. Temporary credentials were sent by email.',
    umDeletedUserConflict: 'A deleted user already uses this username or email. Restore that account instead of creating a duplicate.',
    umCreateFailed: 'Failed to create user',
    umOnlySuperAdminModify: 'Only a super admin can modify a super admin account.',
    umOnlySuperAdminAssign: 'Only a super admin can assign the super admin role.',
    umRoleUpdated: 'User role updated successfully.',
    umRoleUpdateFailed: 'Failed to update user role.',
    umDetailsUpdated: 'User details updated successfully.',
    umDetailsUpdateFailed: 'Failed to update user details.',
    umDeleteReasonPrompt: 'Reason for deleting this user (required):',
    umMovedToTrash: 'User moved to trash successfully.',
    umDeleteFailed: 'Failed to delete user.',
    umRestored: 'User restored successfully.',
    umRestoreFailed: 'Failed to restore user.',
    umDeletedRestored: 'Deleted user restored successfully.',
    umOnlySuperAdminPurge: 'Only a super admin can permanently delete users.',
    umPurgeConfirm: 'Permanently delete this user? This cannot be undone.',
    umPurged: 'User permanently deleted.',
    umPurgeFailed: 'Failed to permanently delete user.',
    umTitle: 'User Management',
    umSubtitle: 'Manage users, deleted accounts, and role assignments',
    umShowDeleted: 'Show deleted users',
    umAddNewUser: '+ Add New User',
    umColUsername: 'Username',
    umColEmail: 'Email',
    umColName: 'Name',
    umColContact: 'Contact',
    umColRole: 'Role',
    umColCreated: 'Created',
    umColActions: 'Actions',
    umRoleViewer: 'Viewer',
    umRoleEditor: 'Editor',
    umRoleAdmin: 'Admin',
    umRoleSuperAdmin: 'Super Admin',
    umDeletedBadge: 'Deleted',
    umRestore: 'Restore',
    umPurge: 'Purge',
    umNoUsers: 'No users.',
    umCreateFirst: 'Create first',
    umAddNewUserTitle: 'Add New User',
    umUsernameLabel: 'Username *',
    umRoleLabel: 'Role *',
    umEmailLabel: 'Email *',
    umFullNameLabel: 'Full Name',
    umContactLabel: 'Contact Number',
    umTempPasswordInfo: 'Temporary password emailed automatically. User changes on first login.',
    umSuperAdminCreateInfo: 'Super admin accounts can only be created by an existing super admin.',
    umConflictTitle: 'Deleted user already matches this account',
    umConflictBody: 'Restore this account instead of creating a duplicate.',
    umRestoreDeletedUser: 'Restore deleted user',
    umCreating: 'Creating...',
    umCreateUser: 'Create User',
    umEditUser: 'Edit {username}',
    umUpdating: 'Updating...',
    umUpdateUser: 'Update User',

    // Activity Logins
    alBackendUnavailable: 'Backend API unavailable',
    alFetchFailed: 'Fetch failed',
    alArchiveFailed: 'Archive failed',
    alSuperAdminRequired: 'Super admin access required',
    alPurgePrompt: 'Type {phrase} to permanently clear all login/logout records.',
    alPurgeSuccess: 'Login history purged successfully.',
    alPurgeFailed: 'Failed to purge login history',
    alSelectLogsFirst: 'Select logs first',
    alActionFailed: '{action} failed',
    alUnknown: 'unknown',
    alColTimestamp: 'Timestamp',
    alColUsername: 'Username',
    alColEvent: 'Event',
    alColStatus: 'Status',
    alColLocation: 'Location',
    alColDeviceType: 'Device Type',
    alColBrowserOs: 'Browser/OS',
    alColDeviceAgent: 'Device/Agent',
    alColIP: 'IP',
    alColArchived: 'Archived',
    alPdfTitle: 'ITDS Login Activity - {tab}',
    alTitle: 'Login Activity',
    alSubtitle: 'Secure archiving and retrieval for audit/compliance.',
    alLastUpdated: 'Last updated',
    alNever: 'Never',
    alExport: 'Export',
    alDateRange: 'Date Range',
    alTo: 'to',
    alAllUsers: 'All Users',
    alDevice: 'Device',
    alLocationPlaceholder: 'City/Country',
    alApply: 'Apply',
    alSelectedCount: '{count} selected',
    alArchive: 'Archive',
    alQuickSearch: 'Quick search...',
    alAutoArchive: 'Auto Archive (90d)',
    alClearAllLoginHistory: 'Clear All Login History',
    alEvents: 'Events',
    alLogins: 'Logins',
    alLogouts: 'Logouts',
    alUsers: 'Users',
    alTabActive: 'ACTIVE',
    alTabArchived: 'ARCHIVED',
    alTabAll: 'ALL',
    alLoading: 'Loading activity...',
    alNoLogsMatch: 'No logs match filters.',

    // Dashboard
    dashboardUserFallback: 'User',
    dashboardExportCSV: 'Export CSV',
    dashboardExportPDF: 'Export PDF',
    dashboardTotalRecordings: 'Total Recordings',
    dashboardAvgSentiment: 'Avg Sentiment',
    dashboardAnalyzedRecords: 'Analyzed Records',
    dashboardThemeSubtitle: 'Stored topic analytics from persisted records.',
    dashboardSentimentSubtitle: 'Distribution of detected sentiment categories',
    dashboardMonthlyTrendsSubtitle: 'Meeting and segment trends over time',
    dashboardUpdated: 'Updated {time}',
    dashboardNoThemeData: 'No theme data available yet.',
    dashboardNoSentimentData: 'No sentiment data available yet.',
    dashboardNoTrendData: 'No monthly trend data available yet.',
    dashboardAIInsights: 'AI Insights',
    dashboardInsightsSubtitle: 'Computed highlights from analyzed segments',
    dashboardNoInsights: 'No insights available yet',
    dashboardRecentActivity7: 'Recent Activity (7 days)',
    dashboardRecentActivitySubtitle: 'Daily meeting and segment counts',
    dashboardNoRecentActivity: 'No recent activity yet',
    dashboardDateNA: 'N/A',
    dashboardActivityStats: '{meetings} meetings, {segments} segments',
    dashboardViewFullHistory: 'View Full History',
    dashboardUnableGenerateReport: 'Unable to generate {format} report right now.',

    // Reports
    reportsNA: 'n/a',
    reportsTitle: 'Reports & Analysis',
    reportsSubtitle: 'View and export AI-generated insights',
    reportsExport: 'Export Report',
    reportsTabSummaries: 'Summaries',
    reportsTabSentiment: 'Sentiment',
    reportsTabActions: 'Action Items',
    reportsTabKeywords: 'Keywords',
    reportsTabTopics: 'Topics',
    reportsRunAI: 'Run AI Analysis',
    reportsRunAnalysis: 'Run Analysis',
    reportsRunning: 'Running...',
    reportsGenerateFor: 'Generate real backend records for {tab}',
    reportsProgress: 'Progress',
    reportsSentimentOverview: 'Sentiment Overview',
    reportsActionStatus: 'Action Items Status',
    reportsNoSentimentRecords: 'No sentiment records available.',
    reportsNoActionRecords: 'No action-item records available.',
    reportsTabReport: '{tab} Report',
    reportsNoData: 'No data available',
    reportsNoBackendRecords: 'No backend records found for this report type.',
    reportsColID: 'ID',
    reportsColSummary: 'Summary',
    reportsColSentiment: 'Sentiment',
    reportsColAction: 'Action',
    reportsColKeywords: 'Keywords',
    reportsColTopic: 'Topic',
    reportsColOccurrences: 'Occurrences',
    reportsColConfidence: 'Confidence',
    reportsColActions: 'Actions',
    reportsPreviewTitle: 'Report Detail Preview',
    reportsPreviewCloseAria: 'Close report preview',
    reportsMinuteActions: 'Minute actions',
    reportsDeleteOnlySentiment: 'Delete this sentiment row only.',
    reportsDeleteOnlyKeyword: 'Delete this keyword row only.',
    reportsDeleteMinuteAndAnalysis: 'Delete minute and analysis.',
    reportsDeleting: 'Deleting...',
    reportsDeleteSentiment: 'Delete Sentiment',
    reportsDeleteKeyword: 'Delete Keyword',
    reportsDeletePlusAnalysis: 'Delete + Analysis',
    reportsFailedLoad: 'Failed to load report data from backend.',
    reportsFailedExport: 'Failed to export report.',
    reportsStartingBatch: 'Starting batch analysis...',
    reportsNoJobId: 'No job id returned from batch start endpoint.',
    reportsStepMeetings: 'Step: {step} | Meetings: {processed}/{total}',
    reportsBatchFailedWorker: 'Batch analysis failed in backend worker.',
    reportsBatchTimeout: 'Batch analysis did not complete in time.',
    reportsNoMeetingsInfo: 'No meetings with segments found. Upload/process meetings first.',
    reportsNoMeetingsStatus: 'No meetings found to process.',
    reportsBatchWarnings: 'Batch completed with warnings: {warning}',
    reportsBatchCompleted: 'Batch analysis completed for {processed} meetings. Refreshing data...',
    reportsBatchRefreshing: 'Batch completed. Refreshing report data...',
    reportsAnalysisFailed: 'Analysis failed. Please check backend logs and try again.',
    reportsFailedStatus: 'Failed: {message}',
    reportsUnknownError: 'Unknown error',
    reportsDeleteNoId: 'This report row does not expose a minute or meeting ID for deletion.',
    reportsDeleteConfirmMinute: 'Delete this minute and its analysis? This will move the minute to trash and clear its analysis.',
    reportsDeleteConfirmSentiment: 'Delete this sentiment row only?',
    reportsDeleteConfirmKeyword: 'Delete this keyword row only?',
    reportsDeletedSentiment: 'Sentiment row deleted.',
    reportsDeletedKeyword: 'Keyword row deleted.',
    reportsDeletedMinuteAnalysis: 'Minute and analysis moved to trash.',
    reportsRowMissing: 'This row was already removed or is no longer available.',
    reportsDeleteFailed: 'Failed to delete this row.',
    reportsSentimentPositive: 'Positive',
    reportsSentimentNeutral: 'Neutral',
    reportsSentimentNegative: 'Negative',
    reportsActionCompleted: 'Completed',
    reportsActionInProgress: 'In Progress',
    reportsActionPending: 'Pending',

    // Search
    searchTitle: 'Search Meeting Minutes',
    searchSubtitle: 'Find specific discussions, decisions, and AI-discovered topics from meeting minutes',
    searchPlaceholderLong: 'Search for topics, decisions, discussions...',
    searchSearch: 'Search',
    searchSearching: 'Searching...',
    searchFilters: 'Filters',
    searchClear: 'Clear',
    searchFilterResults: 'Filter Results',
    searchCategoryTheme: 'Category / Theme',
    searchAllCategories: 'All Categories',
    searchStartDate: 'Start Date',
    searchEndDate: 'End Date',
    searchSentiment: 'Sentiment',
    searchAllSentiments: 'All Sentiments',
    searchPositive: 'Positive',
    searchNeutral: 'Neutral',
    searchNegative: 'Negative',
    searchResults: 'Search Results',
    searchFound: 'found',
    searchNoResults: 'No results found',
    searchTryDifferent: 'Try different keywords or adjust your filters',
    searchDate: 'Date',
    searchCategory: 'Category',
    searchContent: 'Content',
    searchActions: 'Actions',
    searchGeneral: 'General',
    searchQuickFilters: 'Quick Filters',
    searchResultDetail: 'Search Result Detail',
    searchCloseResultPreview: 'Close result preview',
    searchSource: 'Source',
    searchCategoryKeywords: 'Category / Keywords',
    searchNoContent: 'No content available.',
    searchResultOf: 'Result {index} of {total}',
    searchPrevious: 'Previous',
    searchNext: 'Next',
    searchProvideKeywordOrFilter: 'Provide a search keyword or at least one filter.',
    searchServiceUnavailable: 'Search service unavailable right now. Please try again shortly.',

    // Upload
    uploadTitle: 'Upload Meeting Minutes',
    uploadSubtitle: 'Upload PDF, Word, text, or scanned image files for analysis',
    uploadDropOrClick: 'Drop files here or click to upload',
    uploadDocsForAI: 'Upload meeting minutes documents for AI analysis',
    uploadSupportedFormats: 'Supported formats: PDF, Word (DOC, DOCX), Text (TXT), Images (JPG, JPEG, PNG, TIFF, WEBP)',
    uploadMaxSize: 'Maximum file size: 10MB',
    uploadFilesToUpload: 'Files to Upload ({count})',
    uploadClearAll: 'Clear All',
    uploadUploading: 'Uploading...',
    uploadButtonCount: 'Upload {count} file(s)',
    uploadUploadedDocs: 'Uploaded Documents',
    uploadUploadedDocsSubtitle: 'All documents uploaded for analysis',
    uploadTotalDocs: '{count} total',
    uploadRefresh: 'Refresh',
    uploadNoDocsYet: 'No uploaded documents yet',
    uploadNoDocsHint: 'Upload a document above to see it listed here.',
    uploadColDocument: 'Document',
    uploadColMeetingDate: 'Meeting Date',
    uploadColSegments: 'Segments',
    uploadColSummaries: 'Summaries',
    uploadColStatus: 'Status',
    uploadDocumentNumber: 'Document #{id}',
    uploadDocId: 'ID #{id}',
    uploadStatusAnalyzed: 'Analyzed',
    uploadStatusReady: 'Ready for analysis',
    uploadStatusUploaded: 'Uploaded',
    uploadGuidelines: 'Upload Guidelines',
    uploadSupportedFormatsTitle: 'Supported Formats',
    uploadFormatPDF: 'PDF (.pdf)',
    uploadFormatWord: 'Word Document (.doc, .docx)',
    uploadFormatText: 'Text File (.txt)',
    uploadFormatImage: 'Scanned Image (.jpg, .jpeg, .png, .tif, .tiff, .webp)',
    uploadSizeLimitTitle: 'File Size Limit',
    uploadSizeMaximum: 'Maximum: 10MB per file',
    uploadSizeRecommended: 'Recommended: Under 5MB',
    uploadAfterUploadTitle: 'After Upload',
    uploadAfterAnalyze: 'AI will analyze content',
    uploadAfterExtractionTime: 'Extraction takes 1-2 minutes',
    uploadAfterResultsInReports: 'Results appear in Reports',
    uploadExtractionFailed: 'Extraction failed',
    uploadInvalidFileType: 'Invalid file type: {file}',
    uploadFileTooLarge: 'File too large: {file} (maximum 10MB)',
    uploadSelectAtLeastOne: 'Please select at least one file to upload.',
    uploadCompletedWithFailures: 'Uploaded {success} file(s). {failed} file(s) failed.',
    uploadCompletedSuccess: 'Upload complete. {success} file(s) processed successfully.',
    uploadFailedGeneric: 'Upload failed. Please check your files and try again.',
    uploadPhaseQueued: 'Queued for extraction...',
    uploadPhaseUploading: 'Uploading file...',
    uploadPhaseExtracting: 'Extracting document...',
    uploadPhaseSaving: 'Saving extracted content...',
    uploadPhaseCompleted: 'Extraction complete',
    uploadPhaseFailed: 'Extraction failed',

    // Notifications Center
    notificationsSubtitle: 'Push and email history in one place',
    notificationsRefreshing: 'Refreshing...',
    notificationsSent: 'Sent',
    notificationsUnread: 'Unread',
    notificationsReceived: 'Received',
    notificationsArchivedLabel: 'Archived',
    notificationsRead: 'Read',
    notificationsAll: 'All',
    notificationsDeletedLabel: 'Deleted',
    notificationsEmailPush: 'Email / Push',
    notificationsChannelLabel: 'Channel:',
    notificationsScopeLabel: 'Scope',
    notificationsScopeAllUsers: 'All Users',
    notificationsScopeMyAccount: 'My Account',
    notificationsChannelEmail: 'Email',
    notificationsChannelPush: 'Push',
    notificationsChannelMail: 'Mail',
    notificationsStatusSent: 'Sent',
    notificationsStatusDelivered: 'Delivered',
    notificationsStatusFailed: 'Failed',
    notificationsStatusUnknown: 'Unknown',
    notificationsCountTitle: '{label} notifications',
    notificationsNoItems: 'No notifications to display.',
    notificationsUnreadTag: 'UNREAD',
    notificationsByActor: 'by {actor}',
    notificationsMarkRead: 'Mark read',
    notificationsFailedLoad: 'Failed to load notifications.',
    notificationsMarkedRead: 'Marked as read.',
    notificationsMarkReadFailed: 'Failed to mark notification as read.',
    notificationsMarkedAllRead: 'All notifications marked as read.',
    notificationsMarkAllReadFailed: 'Failed to mark all notifications as read.',
    notificationsArchive: 'Archive',
    notificationsArchived: 'Notification archived.',
    notificationsArchiveFailed: 'Failed to archive notification.',
    notificationsRestore: 'Restore',
    notificationsRestored: 'Notification restored.',
    notificationsRestoreFailed: 'Failed to restore notification.',
    notificationsDelete: 'Delete',
    notificationsDeleted: 'Notification deleted.',
    notificationsDeleteFailed: 'Failed to delete notification.',
    notificationsClearAll: 'Clear all',
    notificationsClearingAll: 'Clearing...',
    notificationsClearedAll: 'All notifications cleared.',
    notificationsClearAllFailed: 'Failed to clear notifications.',
    notificationsClearAllConfirm: 'Clear all visible notifications? This will move them to deleted.',
    
    // Dashboard
    welcomeBack: "Welcome back",
    dashboardOverview: "Here's an overview of your board minutes analysis",
    totalMeetings: 'Total Meetings',
    analyzedSegments: 'Analyzed Segments',
    actionItems: 'Action Items',
    themesTracked: 'Themes Tracked',
    themeDistribution: 'Theme Distribution',
    sentimentAnalysis: 'Sentiment Analysis',
    monthlyTrends: 'Monthly Trends',
    recentActivity: 'Recent Activity',
    dashboardCreateEvent: 'Create Event',
    
    // Settings
    managePreferences: 'Manage your application preferences',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    switchTheme: 'Switch between light and dark theme',
    language: 'Language',
    notifications: 'Notifications',
    pushNotifications: 'Push Notifications',
    receiveNotifications: 'Receive notifications in the app',
    emailAlerts: 'Email Alerts',
    receiveEmail: 'Receive email for important updates',
    systemTests: 'System Tests',
    testFeatures: 'Test the integrated features',
    testModelEvaluation: 'Test Model Evaluation',
    testAISummarization: 'Test AI Summarization',
    testSentimentAnalysis: 'Test Sentiment Analysis',
    about: 'About',
    version: 'Version',
    user: 'User',
    role: 'Role',
    
    // Common
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    close: 'Close',
    submit: 'Submit',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    yes: 'Yes',
    no: 'No',
    searchPlaceholder: 'Search...',
    noResults: 'No results found',
  },
  es: {
    // Navigation
    navDashboard: 'Panel',
    navSuperAdmin: 'Súper Admin',
    navCharts: 'Gráficos',
    navSearch: 'Buscar',
    navReports: 'Informes',
    navUpload: 'Subir',
    navUsers: 'Usuarios',
    navActivityLogins: 'Inicios de Sesión Recientes',
    navVoiceRecord: 'Grabación de Voz',
    navTextSimplify: 'Simplificación de Texto',
    navTrendAnalysis: 'Análisis de Tendencias',
    navNotifications: 'Notificaciones',
    navSettings: 'Configuración',
    navAdminTools: 'Herramientas de Admin',
    navProfileSettings: 'Configuración de Perfil',
    navChangePassword: 'Cambiar Contraseña',
    navManageEvents: 'Gestionar Eventos',
    navUploadProfileImage: 'Subir Imagen de Perfil',
    navNoEmail: 'Sin correo',
    navRecentAppEvents: 'Eventos recientes de correo y push de la app',
    navMarkAllRead: 'Marcar todo como leído',
    navMarking: 'Marcando...',
    navViewAll: 'Ver todo',
    navNoRecentNotifications: 'Aún no hay notificaciones recientes.',
    navOpenNotificationCenterForDetails: 'Abre el centro de notificaciones para ver detalles.',
    navLogoutConfirmTitle: '¿Cerrar sesión de tu cuenta?',
    navLogoutConfirm: '¿Seguro que deseas cerrar sesión?',
    navLastUpdated: 'Última actualización',
    navLastUpdatedJustNow: 'Última actualización justo ahora',
    navLastUpdatedRecently: 'Última actualización reciente',
    navLogout: 'Cerrar sesión',

    // Login
    loginSubtitle: 'Inicio de sesión seguro para analiticas, informes y flujos de gobernanza',
    loginUsername: 'Usuario',
    loginUsernamePlaceholder: 'Ingresa tu usuario',
    loginUsernameRequired: 'El usuario es obligatorio',
    loginPassword: 'Contrasena',
    loginPasswordPlaceholder: 'Ingresa tu contrasena',
    loginPasswordRequired: 'La contrasena es obligatoria',
    loginHidePassword: 'Ocultar contrasena',
    loginShowPassword: 'Mostrar contrasena',
    loginSigningIn: 'Iniciando sesion...',
    loginSignInSecurely: 'Iniciar Sesion Segura',
    loginForgotPassword: 'Olvide mi contrasena',
    loginHint: 'Usa tus credenciales asignadas. Las acciones de cuenta se monitorean por seguridad.',
    loginSupport: 'Contacta a tu administrador para obtener acceso',

    // Auth Flow (Change/Reset/Forgot Password)
    authChangePasswordTitle: 'Cambiar Contrasena',
    authMandatoryChangeSubtitle: 'Bienvenido, {username}! Estas usando una contrasena temporal. Cambiala antes de continuar.',
    authOptionalChangeSubtitle: 'Bienvenido de nuevo, {username}! Actualiza tu contrasena.',
    authCurrentPassword: 'Contrasena Actual',
    authCurrentPasswordPlaceholder: 'Ingresa tu contrasena actual',
    authCurrentPasswordRequired: 'La contrasena actual es obligatoria',
    authHideCurrentPassword: 'Ocultar contrasena actual',
    authShowCurrentPassword: 'Mostrar contrasena actual',
    authNewPassword: 'Nueva Contrasena',
    authNewPasswordPlaceholder: 'Crea una contrasena segura',
    authNewPasswordRequired: 'La nueva contrasena es obligatoria',
    authRuleMinLength: 'Minimo 8 caracteres',
    authRuleUppercase: 'Se requiere 1 letra mayuscula',
    authRuleLowercase: 'Se requiere 1 letra minuscula',
    authRuleNumber: 'Se requiere 1 numero',
    authRuleSpecial: 'Se requiere 1 caracter especial',
    authHideNewPassword: 'Ocultar nueva contrasena',
    authShowNewPassword: 'Mostrar nueva contrasena',
    authChecklistLength: '8+ caracteres',
    authChecklistCase: 'Minuscula + Mayuscula',
    authChecklistNumber: 'Numero (0-9)',
    authChecklistSpecial: 'Caracter especial',
    authPasswordStrengthWeak: 'Fortaleza de la contraseña: débil',
    authPasswordStrengthMedium: 'Fortaleza de la contraseña: media',
    authPasswordStrengthStrong: 'Fortaleza de la contraseña: fuerte',
    authConfirmNewPassword: 'Confirmar Nueva Contrasena',
    authConfirmNewPasswordPlaceholder: 'Repite la nueva contrasena',
    authConfirmPasswordRequired: 'Confirma la contrasena',
    authPasswordsDoNotMatch: 'Las contrasenas no coinciden',
    authHideConfirmPassword: 'Ocultar confirmacion de contrasena',
    authShowConfirmPassword: 'Mostrar confirmacion de contrasena',
    authChangeHint: 'Elige una contrasena unica y evita reutilizar credenciales de otros sistemas.',
    authChangingPassword: 'Cambiando Contrasena...',
    authChangeAndContinue: 'Cambiar Contrasena y Continuar',
    authBackToApplication: 'Volver a la Aplicacion',
    authBackToLogin: 'Volver a Login',
    authPasswordMustMeetRequirements: 'La contrasena debe cumplir todos los requisitos anteriores',
    authNewPasswordDifferent: 'La nueva contrasena debe ser diferente a la actual.',
    authPasswordUpdated: 'Contrasena actualizada correctamente. Tu cuenta esta protegida.',
    authChangePasswordFailed: 'El cambio de contrasena fallo. Verifica tu contrasena actual e intenta nuevamente.',
    authResetSuccess: 'Restablecimiento completado. Ahora puedes iniciar sesion con tu nueva contrasena.',
    authResetFailed: 'El restablecimiento fallo. Solicita un nuevo enlace.',
    authInvalidResetTitle: 'Enlace de Restablecimiento Invalido',
    authInvalidResetSubtitle: 'Este enlace falta o es invalido. Solicita un nuevo enlace de restablecimiento.',
    authRequestNewLink: 'Solicitar Nuevo Enlace',
    authResetTitle: 'Restablecer Contrasena',
    authResetSubtitle: 'Crea tu nueva contrasena.',
    authResetHint: 'Usa una contrasena que no hayas usado antes. Guardala de forma segura.',
    authResetting: 'Restableciendo...',
    authResetButton: 'Restablecer Contrasena',
    authResetFooter: 'Este enlace expira en 1 hora. La contrasena debe cumplir los requisitos anteriores.',
    authForgotTitle: 'Olvide mi Contrasena',
    authForgotSubtitle: 'Ingresa tu correo registrado para recibir un enlace seguro de restablecimiento.',
    authEmailAddress: 'Correo Electronico',
    authEmailPlaceholder: 'tu.correo@ejemplo.com',
    authEmailRequired: 'El correo es obligatorio',
    authEmailInvalid: 'Ingresa un correo valido',
    authSendingResetLink: 'Enviando Enlace de Restablecimiento...',
    authSendResetLink: 'Enviar Enlace de Restablecimiento',
    authForgotHint: 'Si el correo existe, se enviara un enlace de restablecimiento. Por seguridad, no revelamos el estado de la cuenta.',
    authForgotSupport: 'Necesitas ayuda? Contacta a tu administrador si ya no tienes acceso a tu bandeja.',
    authForgotRequestReceived: 'Solicitud recibida. Si el correo esta registrado, las instrucciones van en camino.',
    authForgotRequestFailed: 'No pudimos procesar tu solicitud ahora. Intenta nuevamente.',

    // User Management
    umAdminRequired: 'Se requiere acceso de admin para gestion de usuarios.',
    umLoadUsersFailed: 'No se pueden cargar usuarios en este momento.',
    umUserCreated: 'Usuario "{username}" creado correctamente. Credenciales temporales enviadas por correo.',
    umDeletedUserConflict: 'Un usuario eliminado ya usa este usuario o correo. Restaura esa cuenta en vez de crear duplicado.',
    umCreateFailed: 'Error al crear usuario',
    umOnlySuperAdminModify: 'Solo un super admin puede modificar una cuenta super admin.',
    umOnlySuperAdminAssign: 'Solo un super admin puede asignar el rol super admin.',
    umRoleUpdated: 'Rol de usuario actualizado correctamente.',
    umRoleUpdateFailed: 'Error al actualizar rol de usuario.',
    umDetailsUpdated: 'Detalles de usuario actualizados correctamente.',
    umDetailsUpdateFailed: 'Error al actualizar detalles de usuario.',
    umDeleteReasonPrompt: 'Motivo para eliminar este usuario (obligatorio):',
    umMovedToTrash: 'Usuario movido a papelera correctamente.',
    umDeleteFailed: 'Error al eliminar usuario.',
    umRestored: 'Usuario restaurado correctamente.',
    umRestoreFailed: 'Error al restaurar usuario.',
    umDeletedRestored: 'Usuario eliminado restaurado correctamente.',
    umOnlySuperAdminPurge: 'Solo un super admin puede eliminar usuarios permanentemente.',
    umPurgeConfirm: 'Eliminar permanentemente este usuario? Esta accion no se puede deshacer.',
    umPurged: 'Usuario eliminado permanentemente.',
    umPurgeFailed: 'Error al eliminar usuario permanentemente.',
    umTitle: 'Gestion de Usuarios',
    umSubtitle: 'Gestiona usuarios, cuentas eliminadas y asignaciones de rol',
    umShowDeleted: 'Mostrar usuarios eliminados',
    umAddNewUser: '+ Agregar Nuevo Usuario',
    umColUsername: 'Usuario',
    umColEmail: 'Correo',
    umColName: 'Nombre',
    umColContact: 'Contacto',
    umColRole: 'Rol',
    umColCreated: 'Creado',
    umColActions: 'Acciones',
    umRoleViewer: 'Visualizador',
    umRoleEditor: 'Editor',
    umRoleAdmin: 'Admin',
    umRoleSuperAdmin: 'Super Admin',
    umDeletedBadge: 'Eliminado',
    umRestore: 'Restaurar',
    umPurge: 'Purgar',
    umNoUsers: 'Sin usuarios.',
    umCreateFirst: 'Crear primero',
    umAddNewUserTitle: 'Agregar Nuevo Usuario',
    umUsernameLabel: 'Usuario *',
    umRoleLabel: 'Rol *',
    umEmailLabel: 'Correo *',
    umFullNameLabel: 'Nombre Completo',
    umContactLabel: 'Numero de Contacto',
    umTempPasswordInfo: 'Contrasena temporal enviada automaticamente por correo. El usuario la cambia en el primer inicio.',
    umSuperAdminCreateInfo: 'Las cuentas super admin solo pueden ser creadas por un super admin existente.',
    umConflictTitle: 'Usuario eliminado ya coincide con esta cuenta',
    umConflictBody: 'Restaura esta cuenta en vez de crear un duplicado.',
    umRestoreDeletedUser: 'Restaurar usuario eliminado',
    umCreating: 'Creando...',
    umCreateUser: 'Crear Usuario',
    umEditUser: 'Editar {username}',
    umUpdating: 'Actualizando...',
    umUpdateUser: 'Actualizar Usuario',

    // Activity Logins
    alBackendUnavailable: 'API de backend no disponible',
    alFetchFailed: 'Error de carga',
    alArchiveFailed: 'Error al archivar',
    alSuperAdminRequired: 'Se requiere acceso super admin',
    alPurgePrompt: 'Escribe {phrase} para borrar permanentemente todos los registros de login/logout.',
    alPurgeSuccess: 'Historial de login purgado correctamente.',
    alPurgeFailed: 'Error al purgar historial de login',
    alSelectLogsFirst: 'Selecciona logs primero',
    alActionFailed: '{action} fallo',
    alUnknown: 'desconocido',
    alColTimestamp: 'Fecha y Hora',
    alColUsername: 'Usuario',
    alColEvent: 'Evento',
    alColStatus: 'Estado',
    alColLocation: 'Ubicacion',
    alColDeviceType: 'Tipo de Dispositivo',
    alColBrowserOs: 'Navegador/SO',
    alColDeviceAgent: 'Dispositivo/Agente',
    alColIP: 'IP',
    alColArchived: 'Archivado',
    alPdfTitle: 'Actividad de Login ITDS - {tab}',
    alTitle: 'Actividad de Login',
    alSubtitle: 'Archivado y recuperacion segura para auditoria/cumplimiento.',
    alLastUpdated: 'Ultima actualizacion',
    alNever: 'Nunca',
    alExport: 'Exportar',
    alDateRange: 'Rango de Fechas',
    alTo: 'a',
    alAllUsers: 'Todos los Usuarios',
    alDevice: 'Dispositivo',
    alLocationPlaceholder: 'Ciudad/Pais',
    alApply: 'Aplicar',
    alSelectedCount: '{count} seleccionados',
    alArchive: 'Archivar',
    alQuickSearch: 'Busqueda rapida...',
    alAutoArchive: 'Auto Archivar (90d)',
    alClearAllLoginHistory: 'Limpiar Todo el Historial de Login',
    alEvents: 'Eventos',
    alLogins: 'Logins',
    alLogouts: 'Logouts',
    alUsers: 'Usuarios',
    alTabActive: 'ACTIVOS',
    alTabArchived: 'ARCHIVADOS',
    alTabAll: 'TODOS',
    alLoading: 'Cargando actividad...',
    alNoLogsMatch: 'Ningun log coincide con los filtros.',

    // Dashboard
    dashboardUserFallback: 'Usuario',
    dashboardExportCSV: 'Exportar CSV',
    dashboardExportPDF: 'Exportar PDF',
    dashboardTotalRecordings: 'Grabaciones Totales',
    dashboardAvgSentiment: 'Sentimiento Promedio',
    dashboardAnalyzedRecords: 'Registros Analizados',
    dashboardThemeSubtitle: 'Analitica de temas almacenada desde registros persistidos.',
    dashboardSentimentSubtitle: 'Distribucion de categorias de sentimiento detectadas',
    dashboardMonthlyTrendsSubtitle: 'Tendencias de reuniones y segmentos en el tiempo',
    dashboardUpdated: 'Actualizado {time}',
    dashboardNoThemeData: 'Aun no hay datos de temas.',
    dashboardNoSentimentData: 'Aun no hay datos de sentimiento.',
    dashboardNoTrendData: 'Aun no hay datos de tendencias mensuales.',
    dashboardAIInsights: 'Insights de IA',
    dashboardInsightsSubtitle: 'Hallazgos calculados a partir de segmentos analizados',
    dashboardNoInsights: 'Aun no hay insights disponibles',
    dashboardRecentActivity7: 'Actividad Reciente (7 dias)',
    dashboardRecentActivitySubtitle: 'Conteo diario de reuniones y segmentos',
    dashboardNoRecentActivity: 'Aun no hay actividad reciente',
    dashboardDateNA: 'N/D',
    dashboardActivityStats: '{meetings} reuniones, {segments} segmentos',
    dashboardViewFullHistory: 'Ver Historial Completo',
    dashboardUnableGenerateReport: 'No se puede generar el informe {format} ahora.',

    // Reports
    reportsNA: 'n/d',
    reportsTitle: 'Informes y Analisis',
    reportsSubtitle: 'Ver y exportar insights generados por IA',
    reportsExport: 'Exportar Informe',
    reportsTabSummaries: 'Resumenes',
    reportsTabSentiment: 'Sentimiento',
    reportsTabActions: 'Elementos de Accion',
    reportsTabKeywords: 'Palabras Clave',
    reportsTabTopics: 'Temas',
    reportsRunAI: 'Ejecutar Analisis IA',
    reportsRunAnalysis: 'Ejecutar Analisis',
    reportsRunning: 'Ejecutando...',
    reportsGenerateFor: 'Generar registros reales de backend para {tab}',
    reportsProgress: 'Progreso',
    reportsSentimentOverview: 'Resumen de Sentimiento',
    reportsActionStatus: 'Estado de Elementos de Accion',
    reportsNoSentimentRecords: 'No hay registros de sentimiento disponibles.',
    reportsNoActionRecords: 'No hay registros de elementos de accion disponibles.',
    reportsTabReport: 'Informe de {tab}',
    reportsNoData: 'No hay datos disponibles',
    reportsNoBackendRecords: 'No se encontraron registros de backend para este tipo de informe.',
    reportsColID: 'ID',
    reportsColSummary: 'Resumen',
    reportsColSentiment: 'Sentimiento',
    reportsColAction: 'Accion',
    reportsColKeywords: 'Palabras Clave',
    reportsColTopic: 'Tema',
    reportsColOccurrences: 'Ocurrencias',
    reportsColConfidence: 'Confianza',
    reportsColActions: 'Acciones',
    reportsPreviewTitle: 'Vista Previa del Informe',
    reportsPreviewCloseAria: 'Cerrar vista previa del informe',
    reportsMinuteActions: 'Acciones de minuta',
    reportsDeleteOnlySentiment: 'Eliminar solo esta fila de sentimiento.',
    reportsDeleteOnlyKeyword: 'Eliminar solo esta fila de palabra clave.',
    reportsDeleteMinuteAndAnalysis: 'Eliminar minuta y analisis.',
    reportsDeleting: 'Eliminando...',
    reportsDeleteSentiment: 'Eliminar Sentimiento',
    reportsDeleteKeyword: 'Eliminar Palabra Clave',
    reportsDeletePlusAnalysis: 'Eliminar + Analisis',
    reportsFailedLoad: 'No se pudieron cargar los datos del informe desde backend.',
    reportsFailedExport: 'No se pudo exportar el informe.',
    reportsStartingBatch: 'Iniciando analisis por lotes...',
    reportsNoJobId: 'No se devolvio un id de trabajo del endpoint de inicio por lotes.',
    reportsStepMeetings: 'Paso: {step} | Reuniones: {processed}/{total}',
    reportsBatchFailedWorker: 'El analisis por lotes fallo en el worker del backend.',
    reportsBatchTimeout: 'El analisis por lotes no termino a tiempo.',
    reportsNoMeetingsInfo: 'No se encontraron reuniones con segmentos. Sube/procesa reuniones primero.',
    reportsNoMeetingsStatus: 'No se encontraron reuniones para procesar.',
    reportsBatchWarnings: 'Lote completado con advertencias: {warning}',
    reportsBatchCompleted: 'Analisis por lotes completado para {processed} reuniones. Actualizando datos...',
    reportsBatchRefreshing: 'Lote completado. Actualizando datos del informe...',
    reportsAnalysisFailed: 'El analisis fallo. Revisa los logs del backend e intenta de nuevo.',
    reportsFailedStatus: 'Fallo: {message}',
    reportsUnknownError: 'Error desconocido',
    reportsDeleteNoId: 'Esta fila del informe no expone id de minuta o reunion para eliminar.',
    reportsDeleteConfirmMinute: 'Eliminar esta minuta y su analisis? Esto movera la minuta a la papelera y limpiara su analisis.',
    reportsDeleteConfirmSentiment: 'Eliminar solo esta fila de sentimiento?',
    reportsDeleteConfirmKeyword: 'Eliminar solo esta fila de palabra clave?',
    reportsDeletedSentiment: 'Fila de sentimiento eliminada.',
    reportsDeletedKeyword: 'Fila de palabra clave eliminada.',
    reportsDeletedMinuteAnalysis: 'Minuta y analisis movidos a la papelera.',
    reportsRowMissing: 'Esta fila ya fue eliminada o ya no esta disponible.',
    reportsDeleteFailed: 'No se pudo eliminar esta fila.',
    reportsSentimentPositive: 'Positivo',
    reportsSentimentNeutral: 'Neutral',
    reportsSentimentNegative: 'Negativo',
    reportsActionCompleted: 'Completado',
    reportsActionInProgress: 'En Progreso',
    reportsActionPending: 'Pendiente',

    // Search
    searchTitle: 'Buscar Minutas de Reuniones',
    searchSubtitle: 'Encuentra discusiones, decisiones y temas descubiertos por IA en minutas',
    searchPlaceholderLong: 'Buscar temas, decisiones, discusiones...',
    searchSearch: 'Buscar',
    searchSearching: 'Buscando...',
    searchFilters: 'Filtros',
    searchClear: 'Limpiar',
    searchFilterResults: 'Filtrar Resultados',
    searchCategoryTheme: 'Categoria / Tema',
    searchAllCategories: 'Todas las Categorias',
    searchStartDate: 'Fecha de Inicio',
    searchEndDate: 'Fecha Final',
    searchSentiment: 'Sentimiento',
    searchAllSentiments: 'Todos los Sentimientos',
    searchPositive: 'Positivo',
    searchNeutral: 'Neutral',
    searchNegative: 'Negativo',
    searchResults: 'Resultados de Busqueda',
    searchFound: 'encontrados',
    searchNoResults: 'No se encontraron resultados',
    searchTryDifferent: 'Prueba otras palabras clave o ajusta tus filtros',
    searchDate: 'Fecha',
    searchCategory: 'Categoria',
    searchContent: 'Contenido',
    searchActions: 'Acciones',
    searchGeneral: 'General',
    searchQuickFilters: 'Filtros Rapidos',
    searchResultDetail: 'Detalle del Resultado de Busqueda',
    searchCloseResultPreview: 'Cerrar vista previa del resultado',
    searchSource: 'Origen',
    searchCategoryKeywords: 'Categoria / Palabras Clave',
    searchNoContent: 'No hay contenido disponible.',
    searchResultOf: 'Resultado {index} de {total}',
    searchPrevious: 'Anterior',
    searchNext: 'Siguiente',
    searchProvideKeywordOrFilter: 'Proporciona una palabra clave de busqueda o al menos un filtro.',
    searchServiceUnavailable: 'Servicio de busqueda no disponible ahora. Intenta nuevamente en breve.',

    // Upload
    uploadTitle: 'Subir Minutas de Reunion',
    uploadSubtitle: 'Sube archivos PDF, Word, texto o imagen escaneada para analisis',
    uploadDropOrClick: 'Suelta archivos aqui o haz clic para subir',
    uploadDocsForAI: 'Sube documentos de minutas para analisis con IA',
    uploadSupportedFormats: 'Formatos soportados: PDF, Word (DOC, DOCX), Texto (TXT), Imagenes (JPG, JPEG, PNG, TIFF, WEBP)',
    uploadMaxSize: 'Tamano maximo de archivo: 10MB',
    uploadFilesToUpload: 'Archivos para Subir ({count})',
    uploadClearAll: 'Limpiar Todo',
    uploadUploading: 'Subiendo...',
    uploadButtonCount: 'Subir {count} archivo(s)',
    uploadUploadedDocs: 'Documentos Subidos',
    uploadUploadedDocsSubtitle: 'Todos los documentos subidos para analisis',
    uploadTotalDocs: '{count} total',
    uploadRefresh: 'Refrescar',
    uploadNoDocsYet: 'Aun no hay documentos subidos',
    uploadNoDocsHint: 'Sube un documento arriba para verlo aqui.',
    uploadColDocument: 'Documento',
    uploadColMeetingDate: 'Fecha de Reunion',
    uploadColSegments: 'Segmentos',
    uploadColSummaries: 'Resumenes',
    uploadColStatus: 'Estado',
    uploadDocumentNumber: 'Documento #{id}',
    uploadDocId: 'ID #{id}',
    uploadStatusAnalyzed: 'Analizado',
    uploadStatusReady: 'Listo para analisis',
    uploadStatusUploaded: 'Subido',
    uploadGuidelines: 'Guia de Subida',
    uploadSupportedFormatsTitle: 'Formatos Soportados',
    uploadFormatPDF: 'PDF (.pdf)',
    uploadFormatWord: 'Documento Word (.doc, .docx)',
    uploadFormatText: 'Archivo de Texto (.txt)',
    uploadFormatImage: 'Imagen escaneada (.jpg, .jpeg, .png, .tif, .tiff, .webp)',
    uploadSizeLimitTitle: 'Limite de Tamano',
    uploadSizeMaximum: 'Maximo: 10MB por archivo',
    uploadSizeRecommended: 'Recomendado: Menor a 5MB',
    uploadAfterUploadTitle: 'Despues de Subir',
    uploadAfterAnalyze: 'La IA analizara el contenido',
    uploadAfterExtractionTime: 'La extraccion toma 1-2 minutos',
    uploadAfterResultsInReports: 'Los resultados aparecen en Informes',
    uploadExtractionFailed: 'Fallo la extraccion',
    uploadInvalidFileType: 'Tipo de archivo invalido: {file}',
    uploadFileTooLarge: 'Archivo demasiado grande: {file} (maximo 10MB)',
    uploadSelectAtLeastOne: 'Selecciona al menos un archivo para subir.',
    uploadCompletedWithFailures: 'Se subieron {success} archivo(s). {failed} archivo(s) fallaron.',
    uploadCompletedSuccess: 'Subida completa. {success} archivo(s) procesados correctamente.',
    uploadFailedGeneric: 'La subida fallo. Revisa tus archivos e intenta nuevamente.',
    uploadPhaseQueued: 'En cola para extraccion...',
    uploadPhaseUploading: 'Subiendo archivo...',
    uploadPhaseExtracting: 'Extrayendo documento...',
    uploadPhaseSaving: 'Guardando contenido extraido...',
    uploadPhaseCompleted: 'Extraccion completa',
    uploadPhaseFailed: 'Extraccion fallida',

    // Notifications Center
    notificationsSubtitle: 'Historial de push y correo en un solo lugar',
    notificationsRefreshing: 'Refrescando...',
    notificationsSent: 'Enviadas',
    notificationsUnread: 'No Leidas',
    notificationsReceived: 'Recibidas',
    notificationsArchivedLabel: 'Archivadas',
    notificationsRead: 'Leidas',
    notificationsAll: 'Todas',
    notificationsDeletedLabel: 'Eliminadas',
    notificationsEmailPush: 'Correo / Push',
    notificationsChannelLabel: 'Canal:',
    notificationsScopeLabel: 'Alcance',
    notificationsScopeAllUsers: 'Todos los Usuarios',
    notificationsScopeMyAccount: 'Mi Cuenta',
    notificationsChannelEmail: 'Correo',
    notificationsChannelPush: 'Push',
    notificationsChannelMail: 'Correo',
    notificationsStatusSent: 'Enviado',
    notificationsStatusDelivered: 'Entregado',
    notificationsStatusFailed: 'Fallido',
    notificationsStatusUnknown: 'Desconocido',
    notificationsCountTitle: 'Notificaciones {label}',
    notificationsNoItems: 'No hay notificaciones para mostrar.',
    notificationsUnreadTag: 'NO LEIDA',
    notificationsByActor: 'por {actor}',
    notificationsMarkRead: 'Marcar leida',
    notificationsFailedLoad: 'No se pudieron cargar las notificaciones.',
    notificationsMarkedRead: 'Marcada como leida.',
    notificationsMarkReadFailed: 'No se pudo marcar la notificacion como leida.',
    notificationsMarkedAllRead: 'Todas las notificaciones se marcaron como leidas.',
    notificationsMarkAllReadFailed: 'No se pudieron marcar todas las notificaciones como leidas.',
    notificationsArchive: 'Archivar',
    notificationsArchived: 'Notificacion archivada.',
    notificationsArchiveFailed: 'No se pudo archivar la notificacion.',
    notificationsRestore: 'Restaurar',
    notificationsRestored: 'Notificacion restaurada.',
    notificationsRestoreFailed: 'No se pudo restaurar la notificacion.',
    notificationsDelete: 'Eliminar',
    notificationsDeleted: 'Notificacion eliminada.',
    notificationsDeleteFailed: 'No se pudo eliminar la notificacion.',
    notificationsClearAll: 'Limpiar todo',
    notificationsClearingAll: 'Limpiando...',
    notificationsClearedAll: 'Todas las notificaciones fueron limpiadas.',
    notificationsClearAllFailed: 'No se pudieron limpiar las notificaciones.',
    notificationsClearAllConfirm: '¿Limpiar todas las notificaciones visibles? Se moverán a eliminadas.',
    
    // Dashboard
    welcomeBack: "Bienvenido de nuevo",
    dashboardOverview: "Aquí tienes una visión general del análisis de las actas de la junta",
    totalMeetings: 'Reuniones Totales',
    analyzedSegments: 'Segmentos Analizados',
    actionItems: 'Elementos de Acción',
    themesTracked: 'Temas Rastreados',
    themeDistribution: 'Distribución de Temas',
    sentimentAnalysis: 'Análisis de Sentimiento',
    monthlyTrends: 'Tendencias Mensuales',
    recentActivity: 'Actividad Reciente',
    dashboardCreateEvent: 'Crear Evento',
    
    // Settings
    managePreferences: 'Gestiona tus preferencias de aplicación',
    appearance: 'Apariencia',
    darkMode: 'Modo Oscuro',
    switchTheme: 'Cambiar entre tema claro y oscuro',
    language: 'Idioma',
    notifications: 'Notificaciones',
    pushNotifications: 'Notificaciones Push',
    receiveNotifications: 'Recibir notificaciones en la aplicación',
    emailAlerts: 'Alertas de Correo',
    receiveEmail: 'Recibir correo para actualizaciones importantes',
    systemTests: 'Pruebas del Sistema',
    testFeatures: 'Prueba las características integradas',
    testModelEvaluation: 'Probar Evaluación del Modelo',
    testAISummarization: 'Probar Resumen de IA',
    testSentimentAnalysis: 'Probar Análisis de Sentimiento',
    about: 'Acerca de',
    version: 'Versión',
    user: 'Usuario',
    role: 'Rol',
    
    // Common
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    view: 'Ver',
    close: 'Cerrar',
    submit: 'Enviar',
    success: 'Éxito',
    error: 'Error',
    warning: 'Advertencia',
    info: 'Información',
    yes: 'Sí',
    no: 'No',
    searchPlaceholder: 'Buscar...',
    noResults: 'No se encontraron resultados',
  },
  fr: {
    // Navigation
    navDashboard: 'Tableau de bord',
    navSuperAdmin: 'Super Admin',
    navCharts: 'Graphiques',
    navSearch: 'Rechercher',
    navReports: 'Rapports',
    navUpload: 'Télécharger',
    navUsers: 'Utilisateurs',
    navActivityLogins: 'Connexions Récentes',
    navVoiceRecord: 'Enregistrement Vocal',
    navTextSimplify: 'Simplification de Texte',
    navTrendAnalysis: 'Analyse des Tendances',
    navNotifications: 'Notifications',
    navSettings: 'Paramètres',
    navAdminTools: 'Outils Admin',
    navProfileSettings: 'Paramètres du Profil',
    navChangePassword: 'Changer le Mot de Passe',
    navManageEvents: 'Gérer les Événements',
    navUploadProfileImage: 'Télécharger une Image de Profil',
    navNoEmail: 'Pas d\'email',
    navRecentAppEvents: 'Événements récents de mails et push de l\'app',
    navMarkAllRead: 'Tout marquer comme lu',
    navMarking: 'Marquage...',
    navViewAll: 'Voir tout',
    navNoRecentNotifications: 'Aucune notification récente pour le moment.',
    navOpenNotificationCenterForDetails: 'Ouvrez le centre de notifications pour les détails.',
    navLogoutConfirmTitle: 'Voulez-vous vous déconnecter ?',
    navLogoutConfirm: 'Voulez-vous vraiment vous déconnecter ?',
    navLastUpdated: 'Dernière mise à jour',
    navLastUpdatedJustNow: 'Dernière mise à jour à l\'instant',
    navLastUpdatedRecently: 'Dernière mise à jour récente',
    navLogout: 'Déconnexion',

    // Login
    loginSubtitle: 'Connexion securisee pour les analyses, rapports et flux de gouvernance',
    loginUsername: 'Nom d\'utilisateur',
    loginUsernamePlaceholder: 'Saisissez votre nom d\'utilisateur',
    loginUsernameRequired: 'Le nom d\'utilisateur est requis',
    loginPassword: 'Mot de passe',
    loginPasswordPlaceholder: 'Saisissez votre mot de passe',
    loginPasswordRequired: 'Le mot de passe est requis',
    loginHidePassword: 'Masquer le mot de passe',
    loginShowPassword: 'Afficher le mot de passe',
    loginSigningIn: 'Connexion en cours...',
    loginSignInSecurely: 'Se Connecter en Securite',
    loginForgotPassword: 'Mot de passe oublie',
    loginHint: 'Utilisez vos identifiants assignes. Les actions du compte sont surveillees pour la securite.',
    loginSupport: 'Contactez votre administrateur pour obtenir l\'acces',

    // Auth Flow (Change/Reset/Forgot Password)
    authChangePasswordTitle: 'Changer le Mot de Passe',
    authMandatoryChangeSubtitle: 'Bienvenue, {username}! Vous utilisez un mot de passe temporaire. Veuillez le changer avant de continuer.',
    authOptionalChangeSubtitle: 'Bon retour, {username}! Mettez a jour votre mot de passe.',
    authCurrentPassword: 'Mot de Passe Actuel',
    authCurrentPasswordPlaceholder: 'Entrez votre mot de passe actuel',
    authCurrentPasswordRequired: 'Le mot de passe actuel est requis',
    authHideCurrentPassword: 'Masquer le mot de passe actuel',
    authShowCurrentPassword: 'Afficher le mot de passe actuel',
    authNewPassword: 'Nouveau Mot de Passe',
    authNewPasswordPlaceholder: 'Creez un mot de passe fort',
    authNewPasswordRequired: 'Le nouveau mot de passe est requis',
    authRuleMinLength: 'Minimum 8 caracteres',
    authRuleUppercase: '1 lettre majuscule requise',
    authRuleLowercase: '1 lettre minuscule requise',
    authRuleNumber: '1 chiffre requis',
    authRuleSpecial: '1 caractere special requis',
    authHideNewPassword: 'Masquer le nouveau mot de passe',
    authShowNewPassword: 'Afficher le nouveau mot de passe',
    authChecklistLength: '8+ caracteres',
    authChecklistCase: 'Minuscule + Majuscule',
    authChecklistNumber: 'Nombre (0-9)',
    authChecklistSpecial: 'Caractere special',
    authPasswordStrengthWeak: 'Force du mot de passe : faible',
    authPasswordStrengthMedium: 'Force du mot de passe : moyenne',
    authPasswordStrengthStrong: 'Force du mot de passe : forte',
    authConfirmNewPassword: 'Confirmer le Nouveau Mot de Passe',
    authConfirmNewPasswordPlaceholder: 'Repetez le nouveau mot de passe',
    authConfirmPasswordRequired: 'Veuillez confirmer le mot de passe',
    authPasswordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    authHideConfirmPassword: 'Masquer la confirmation du mot de passe',
    authShowConfirmPassword: 'Afficher la confirmation du mot de passe',
    authChangeHint: 'Choisissez un mot de passe unique et evitez de reutiliser des identifiants d\'autres systemes.',
    authChangingPassword: 'Changement du Mot de Passe...',
    authChangeAndContinue: 'Changer le Mot de Passe et Continuer',
    authBackToApplication: 'Retour a l\'Application',
    authBackToLogin: 'Retour a la Connexion',
    authPasswordMustMeetRequirements: 'Le mot de passe doit respecter toutes les exigences ci-dessus',
    authNewPasswordDifferent: 'Le nouveau mot de passe doit etre different du mot de passe actuel.',
    authPasswordUpdated: 'Mot de passe mis a jour avec succes. Votre compte est maintenant securise.',
    authChangePasswordFailed: 'Le changement du mot de passe a echoue. Verifiez votre mot de passe actuel puis reessayez.',
    authResetSuccess: 'Reinitialisation terminee. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    authResetFailed: 'La reinitialisation a echoue. Veuillez demander un nouveau lien.',
    authInvalidResetTitle: 'Lien de Reinitialisation Invalide',
    authInvalidResetSubtitle: 'Ce lien est manquant ou invalide. Demandez un nouveau lien de reinitialisation.',
    authRequestNewLink: 'Demander un Nouveau Lien',
    authResetTitle: 'Reinitialiser le Mot de Passe',
    authResetSubtitle: 'Creez votre nouveau mot de passe.',
    authResetHint: 'Utilisez un mot de passe jamais utilise auparavant. Conservez-le en securite.',
    authResetting: 'Reinitialisation...',
    authResetButton: 'Reinitialiser le Mot de Passe',
    authResetFooter: 'Ce lien expire dans 1 heure. Le mot de passe doit respecter les exigences ci-dessus.',
    authForgotTitle: 'Mot de Passe Oublie',
    authForgotSubtitle: 'Entrez votre email enregistre pour recevoir un lien de reinitialisation securise.',
    authEmailAddress: 'Adresse Email',
    authEmailPlaceholder: 'votre.email@exemple.com',
    authEmailRequired: 'L\'email est requis',
    authEmailInvalid: 'Entrez une adresse email valide',
    authSendingResetLink: 'Envoi du Lien de Reinitialisation...',
    authSendResetLink: 'Envoyer le Lien de Reinitialisation',
    authForgotHint: 'Si l\'email existe, un lien de reinitialisation sera envoye. Pour la securite, nous ne revelons pas le statut du compte.',
    authForgotSupport: 'Besoin d\'aide? Contactez votre administrateur si vous n\'avez plus acces a votre boite mail.',
    authForgotRequestReceived: 'Demande recue. Si cet email est enregistre, les instructions sont en route.',
    authForgotRequestFailed: 'Nous ne pouvons pas traiter votre demande maintenant. Veuillez reessayer.',

    // User Management
    umAdminRequired: 'Acces admin requis pour la gestion des utilisateurs.',
    umLoadUsersFailed: 'Impossible de charger les utilisateurs pour le moment.',
    umUserCreated: 'Utilisateur "{username}" cree avec succes. Des identifiants temporaires ont ete envoyes par email.',
    umDeletedUserConflict: 'Un utilisateur supprime utilise deja ce nom ou email. Restaurez ce compte au lieu de creer un doublon.',
    umCreateFailed: 'Echec de creation utilisateur',
    umOnlySuperAdminModify: 'Seul un super admin peut modifier un compte super admin.',
    umOnlySuperAdminAssign: 'Seul un super admin peut attribuer le role super admin.',
    umRoleUpdated: 'Role utilisateur mis a jour avec succes.',
    umRoleUpdateFailed: 'Echec de mise a jour du role utilisateur.',
    umDetailsUpdated: 'Details utilisateur mis a jour avec succes.',
    umDetailsUpdateFailed: 'Echec de mise a jour des details utilisateur.',
    umDeleteReasonPrompt: 'Raison de suppression de cet utilisateur (obligatoire):',
    umMovedToTrash: 'Utilisateur deplace vers la corbeille avec succes.',
    umDeleteFailed: 'Echec de suppression utilisateur.',
    umRestored: 'Utilisateur restaure avec succes.',
    umRestoreFailed: 'Echec de restauration utilisateur.',
    umDeletedRestored: 'Utilisateur supprime restaure avec succes.',
    umOnlySuperAdminPurge: 'Seul un super admin peut supprimer des utilisateurs definitivement.',
    umPurgeConfirm: 'Supprimer cet utilisateur definitivement ? Cette action est irreversible.',
    umPurged: 'Utilisateur supprime definitivement.',
    umPurgeFailed: 'Echec de suppression definitive utilisateur.',
    umTitle: 'Gestion des Utilisateurs',
    umSubtitle: 'Gerez les utilisateurs, comptes supprimes et attributions de roles',
    umShowDeleted: 'Afficher les utilisateurs supprimes',
    umAddNewUser: '+ Ajouter un Nouvel Utilisateur',
    umColUsername: 'Nom Utilisateur',
    umColEmail: 'Email',
    umColName: 'Nom',
    umColContact: 'Contact',
    umColRole: 'Role',
    umColCreated: 'Cree le',
    umColActions: 'Actions',
    umRoleViewer: 'Lecteur',
    umRoleEditor: 'Editeur',
    umRoleAdmin: 'Admin',
    umRoleSuperAdmin: 'Super Admin',
    umDeletedBadge: 'Supprime',
    umRestore: 'Restaurer',
    umPurge: 'Purger',
    umNoUsers: 'Aucun utilisateur.',
    umCreateFirst: 'Creer le premier',
    umAddNewUserTitle: 'Ajouter un Nouvel Utilisateur',
    umUsernameLabel: 'Nom Utilisateur *',
    umRoleLabel: 'Role *',
    umEmailLabel: 'Email *',
    umFullNameLabel: 'Nom Complet',
    umContactLabel: 'Numero de Contact',
    umTempPasswordInfo: 'Mot de passe temporaire envoye automatiquement par email. L\'utilisateur le change a la premiere connexion.',
    umSuperAdminCreateInfo: 'Les comptes super admin ne peuvent etre crees que par un super admin existant.',
    umConflictTitle: 'Un utilisateur supprime correspond deja a ce compte',
    umConflictBody: 'Restaurez ce compte au lieu de creer un doublon.',
    umRestoreDeletedUser: 'Restaurer utilisateur supprime',
    umCreating: 'Creation...',
    umCreateUser: 'Creer Utilisateur',
    umEditUser: 'Editer {username}',
    umUpdating: 'Mise a jour...',
    umUpdateUser: 'Mettre a Jour Utilisateur',

    // Activity Logins
    alBackendUnavailable: 'API backend indisponible',
    alFetchFailed: 'Echec de recuperation',
    alArchiveFailed: 'Echec d\'archivage',
    alSuperAdminRequired: 'Acces super admin requis',
    alPurgePrompt: 'Tapez {phrase} pour effacer definitivement tous les enregistrements login/logout.',
    alPurgeSuccess: 'Historique de connexion purge avec succes.',
    alPurgeFailed: 'Echec de purge de l\'historique de connexion',
    alSelectLogsFirst: 'Selectionnez d\'abord des logs',
    alActionFailed: '{action} a echoue',
    alUnknown: 'inconnu',
    alColTimestamp: 'Horodatage',
    alColUsername: 'Nom Utilisateur',
    alColEvent: 'Evenement',
    alColStatus: 'Statut',
    alColLocation: 'Localisation',
    alColDeviceType: 'Type Appareil',
    alColBrowserOs: 'Navigateur/OS',
    alColDeviceAgent: 'Appareil/Agent',
    alColIP: 'IP',
    alColArchived: 'Archive',
    alPdfTitle: 'Activite de Connexion ITDS - {tab}',
    alTitle: 'Activite de Connexion',
    alSubtitle: 'Archivage et recuperation securises pour audit/conformite.',
    alLastUpdated: 'Derniere mise a jour',
    alNever: 'Jamais',
    alExport: 'Exporter',
    alDateRange: 'Plage de Dates',
    alTo: 'a',
    alAllUsers: 'Tous les Utilisateurs',
    alDevice: 'Appareil',
    alLocationPlaceholder: 'Ville/Pays',
    alApply: 'Appliquer',
    alSelectedCount: '{count} selectionnes',
    alArchive: 'Archiver',
    alQuickSearch: 'Recherche rapide...',
    alAutoArchive: 'Archivage Auto (90j)',
    alClearAllLoginHistory: 'Effacer Tout l\'Historique de Connexion',
    alEvents: 'Evenements',
    alLogins: 'Connexions',
    alLogouts: 'Deconnexions',
    alUsers: 'Utilisateurs',
    alTabActive: 'ACTIFS',
    alTabArchived: 'ARCHIVES',
    alTabAll: 'TOUS',
    alLoading: 'Chargement de l\'activite...',
    alNoLogsMatch: 'Aucun log ne correspond aux filtres.',

    // Dashboard
    dashboardUserFallback: 'Utilisateur',
    dashboardExportCSV: 'Exporter CSV',
    dashboardExportPDF: 'Exporter PDF',
    dashboardTotalRecordings: 'Enregistrements Totaux',
    dashboardAvgSentiment: 'Sentiment Moyen',
    dashboardAnalyzedRecords: 'Enregistrements Analyses',
    dashboardThemeSubtitle: 'Analytique des themes stockes a partir des enregistrements persistants.',
    dashboardSentimentSubtitle: 'Distribution des categories de sentiment detectees',
    dashboardMonthlyTrendsSubtitle: 'Tendances des reunions et segments dans le temps',
    dashboardUpdated: 'Mis a jour {time}',
    dashboardNoThemeData: 'Aucune donnee de theme disponible pour le moment.',
    dashboardNoSentimentData: 'Aucune donnee de sentiment disponible pour le moment.',
    dashboardNoTrendData: 'Aucune donnee de tendance mensuelle disponible pour le moment.',
    dashboardAIInsights: 'Insights IA',
    dashboardInsightsSubtitle: 'Points forts calcules a partir des segments analyses',
    dashboardNoInsights: 'Aucun insight disponible pour le moment',
    dashboardRecentActivity7: 'Activite Recente (7 jours)',
    dashboardRecentActivitySubtitle: 'Nombre quotidien de reunions et segments',
    dashboardNoRecentActivity: 'Aucune activite recente pour le moment',
    dashboardDateNA: 'N/D',
    dashboardActivityStats: '{meetings} reunions, {segments} segments',
    dashboardViewFullHistory: 'Voir l\'historique complet',
    dashboardUnableGenerateReport: 'Impossible de generer le rapport {format} pour le moment.',

    // Reports
    reportsNA: 'n/a',
    reportsTitle: 'Rapports et Analyse',
    reportsSubtitle: 'Voir et exporter les insights generes par IA',
    reportsExport: 'Exporter le Rapport',
    reportsTabSummaries: 'Resumes',
    reportsTabSentiment: 'Sentiment',
    reportsTabActions: 'Elements d\'Action',
    reportsTabKeywords: 'Mots Cles',
    reportsTabTopics: 'Sujets',
    reportsRunAI: 'Lancer l\'Analyse IA',
    reportsRunAnalysis: 'Lancer Analyse',
    reportsRunning: 'Execution...',
    reportsGenerateFor: 'Generer des enregistrements backend reels pour {tab}',
    reportsProgress: 'Progression',
    reportsSentimentOverview: 'Apercu du Sentiment',
    reportsActionStatus: 'Statut des Elements d\'Action',
    reportsNoSentimentRecords: 'Aucun enregistrement de sentiment disponible.',
    reportsNoActionRecords: 'Aucun enregistrement d\'element d\'action disponible.',
    reportsTabReport: 'Rapport {tab}',
    reportsNoData: 'Aucune donnee disponible',
    reportsNoBackendRecords: 'Aucun enregistrement backend trouve pour ce type de rapport.',
    reportsColID: 'ID',
    reportsColSummary: 'Resume',
    reportsColSentiment: 'Sentiment',
    reportsColAction: 'Action',
    reportsColKeywords: 'Mots Cles',
    reportsColTopic: 'Sujet',
    reportsColOccurrences: 'Occurrences',
    reportsColConfidence: 'Confiance',
    reportsColActions: 'Actions',
    reportsPreviewTitle: 'Apercu Detaille du Rapport',
    reportsPreviewCloseAria: 'Fermer l\'apercu du rapport',
    reportsMinuteActions: 'Actions minute',
    reportsDeleteOnlySentiment: 'Supprimer uniquement cette ligne de sentiment.',
    reportsDeleteOnlyKeyword: 'Supprimer uniquement cette ligne de mot cle.',
    reportsDeleteMinuteAndAnalysis: 'Supprimer minute et analyse.',
    reportsDeleting: 'Suppression...',
    reportsDeleteSentiment: 'Supprimer Sentiment',
    reportsDeleteKeyword: 'Supprimer Mot Cle',
    reportsDeletePlusAnalysis: 'Supprimer + Analyse',
    reportsFailedLoad: 'Echec du chargement des donnees de rapport depuis le backend.',
    reportsFailedExport: 'Echec de l\'export du rapport.',
    reportsStartingBatch: 'Demarrage de l\'analyse par lot...',
    reportsNoJobId: 'Aucun id de job retourne par le point de depart du lot.',
    reportsStepMeetings: 'Etape: {step} | Reunions: {processed}/{total}',
    reportsBatchFailedWorker: 'L\'analyse par lot a echoue dans le worker backend.',
    reportsBatchTimeout: 'L\'analyse par lot ne s\'est pas terminee a temps.',
    reportsNoMeetingsInfo: 'Aucune reunion avec segments trouvee. Importez/traitez d\'abord des reunions.',
    reportsNoMeetingsStatus: 'Aucune reunion trouvee a traiter.',
    reportsBatchWarnings: 'Lot termine avec avertissements: {warning}',
    reportsBatchCompleted: 'Analyse par lot terminee pour {processed} reunions. Actualisation des donnees...',
    reportsBatchRefreshing: 'Lot termine. Actualisation des donnees du rapport...',
    reportsAnalysisFailed: 'L\'analyse a echoue. Verifiez les logs backend et reessayez.',
    reportsFailedStatus: 'Echec: {message}',
    reportsUnknownError: 'Erreur inconnue',
    reportsDeleteNoId: 'Cette ligne de rapport ne fournit aucun id de minute ou reunion pour suppression.',
    reportsDeleteConfirmMinute: 'Supprimer cette minute et son analyse ? Cela deplacera la minute vers la corbeille et effacera son analyse.',
    reportsDeleteConfirmSentiment: 'Supprimer uniquement cette ligne de sentiment ?',
    reportsDeleteConfirmKeyword: 'Supprimer uniquement cette ligne de mot cle ?',
    reportsDeletedSentiment: 'Ligne de sentiment supprimee.',
    reportsDeletedKeyword: 'Ligne de mot cle supprimee.',
    reportsDeletedMinuteAnalysis: 'Minute et analyse deplacees vers la corbeille.',
    reportsRowMissing: 'Cette ligne a deja ete supprimee ou n\'est plus disponible.',
    reportsDeleteFailed: 'Impossible de supprimer cette ligne.',
    reportsSentimentPositive: 'Positif',
    reportsSentimentNeutral: 'Neutre',
    reportsSentimentNegative: 'Negatif',
    reportsActionCompleted: 'Termine',
    reportsActionInProgress: 'En Cours',
    reportsActionPending: 'En Attente',

    // Search
    searchTitle: 'Rechercher dans les Minutes de Reunion',
    searchSubtitle: 'Trouvez des discussions, decisions et sujets detectes par IA dans les minutes',
    searchPlaceholderLong: 'Rechercher des sujets, decisions, discussions...',
    searchSearch: 'Rechercher',
    searchSearching: 'Recherche...',
    searchFilters: 'Filtres',
    searchClear: 'Effacer',
    searchFilterResults: 'Filtrer les Resultats',
    searchCategoryTheme: 'Categorie / Theme',
    searchAllCategories: 'Toutes les Categories',
    searchStartDate: 'Date de Debut',
    searchEndDate: 'Date de Fin',
    searchSentiment: 'Sentiment',
    searchAllSentiments: 'Tous les Sentiments',
    searchPositive: 'Positif',
    searchNeutral: 'Neutre',
    searchNegative: 'Negatif',
    searchResults: 'Resultats de Recherche',
    searchFound: 'trouves',
    searchNoResults: 'Aucun resultat trouve',
    searchTryDifferent: 'Essayez d\'autres mots-cles ou ajustez vos filtres',
    searchDate: 'Date',
    searchCategory: 'Categorie',
    searchContent: 'Contenu',
    searchActions: 'Actions',
    searchGeneral: 'General',
    searchQuickFilters: 'Filtres Rapides',
    searchResultDetail: 'Detail du Resultat de Recherche',
    searchCloseResultPreview: 'Fermer l\'apercu du resultat',
    searchSource: 'Source',
    searchCategoryKeywords: 'Categorie / Mots Cles',
    searchNoContent: 'Aucun contenu disponible.',
    searchResultOf: 'Resultat {index} sur {total}',
    searchPrevious: 'Precedent',
    searchNext: 'Suivant',
    searchProvideKeywordOrFilter: 'Fournissez un mot-cle de recherche ou au moins un filtre.',
    searchServiceUnavailable: 'Service de recherche indisponible pour le moment. Reessayez sous peu.',

    // Upload
    uploadTitle: 'Televerser les Minutes de Reunion',
    uploadSubtitle: 'Televersez des fichiers PDF, Word, texte ou images numerisees pour analyse',
    uploadDropOrClick: 'Deposez les fichiers ici ou cliquez pour televerser',
    uploadDocsForAI: 'Televersez les documents de minutes pour analyse IA',
    uploadSupportedFormats: 'Formats pris en charge: PDF, Word (DOC, DOCX), Texte (TXT), Images (JPG, JPEG, PNG, TIFF, WEBP)',
    uploadMaxSize: 'Taille maximale du fichier: 10MB',
    uploadFilesToUpload: 'Fichiers a Televerser ({count})',
    uploadClearAll: 'Tout Effacer',
    uploadUploading: 'Televersement...',
    uploadButtonCount: 'Televerser {count} fichier(s)',
    uploadUploadedDocs: 'Documents Televerses',
    uploadUploadedDocsSubtitle: 'Tous les documents televerses pour analyse',
    uploadTotalDocs: '{count} total',
    uploadRefresh: 'Actualiser',
    uploadNoDocsYet: 'Aucun document televerse pour le moment',
    uploadNoDocsHint: 'Televersez un document ci-dessus pour le voir liste ici.',
    uploadColDocument: 'Document',
    uploadColMeetingDate: 'Date de Reunion',
    uploadColSegments: 'Segments',
    uploadColSummaries: 'Resumes',
    uploadColStatus: 'Statut',
    uploadDocumentNumber: 'Document #{id}',
    uploadDocId: 'ID #{id}',
    uploadStatusAnalyzed: 'Analyse',
    uploadStatusReady: 'Pret pour analyse',
    uploadStatusUploaded: 'Televerse',
    uploadGuidelines: 'Guide de Televersement',
    uploadSupportedFormatsTitle: 'Formats Pris en Charge',
    uploadFormatPDF: 'PDF (.pdf)',
    uploadFormatWord: 'Document Word (.doc, .docx)',
    uploadFormatText: 'Fichier Texte (.txt)',
    uploadFormatImage: 'Image numerisee (.jpg, .jpeg, .png, .tif, .tiff, .webp)',
    uploadSizeLimitTitle: 'Limite de Taille',
    uploadSizeMaximum: 'Maximum: 10MB par fichier',
    uploadSizeRecommended: 'Recommande: Moins de 5MB',
    uploadAfterUploadTitle: 'Apres Televersement',
    uploadAfterAnalyze: 'IA analysera le contenu',
    uploadAfterExtractionTime: 'L\'extraction prend 1-2 minutes',
    uploadAfterResultsInReports: 'Les resultats apparaissent dans Rapports',
    uploadExtractionFailed: 'Extraction echouee',
    uploadInvalidFileType: 'Type de fichier invalide: {file}',
    uploadFileTooLarge: 'Fichier trop volumineux: {file} (maximum 10MB)',
    uploadSelectAtLeastOne: 'Veuillez selectionner au moins un fichier a televerser.',
    uploadCompletedWithFailures: '{success} fichier(s) televerses. {failed} fichier(s) ont echoue.',
    uploadCompletedSuccess: 'Televersement termine. {success} fichier(s) traites avec succes.',
    uploadFailedGeneric: 'Echec du televersement. Verifiez vos fichiers et reessayez.',
    uploadPhaseQueued: 'En file pour extraction...',
    uploadPhaseUploading: 'Televersement du fichier...',
    uploadPhaseExtracting: 'Extraction du document...',
    uploadPhaseSaving: 'Sauvegarde du contenu extrait...',
    uploadPhaseCompleted: 'Extraction terminee',
    uploadPhaseFailed: 'Extraction echouee',

    // Notifications Center
    notificationsSubtitle: 'Historique push et email au meme endroit',
    notificationsRefreshing: 'Actualisation...',
    notificationsSent: 'Envoyees',
    notificationsUnread: 'Non Lues',
    notificationsReceived: 'Recues',
    notificationsArchivedLabel: 'Archivees',
    notificationsRead: 'Lues',
    notificationsAll: 'Toutes',
    notificationsDeletedLabel: 'Supprimees',
    notificationsEmailPush: 'Email / Push',
    notificationsChannelLabel: 'Canal:',
    notificationsScopeLabel: 'Portee',
    notificationsScopeAllUsers: 'Tous les Utilisateurs',
    notificationsScopeMyAccount: 'Mon Compte',
    notificationsChannelEmail: 'Email',
    notificationsChannelPush: 'Push',
    notificationsChannelMail: 'Mail',
    notificationsStatusSent: 'Envoye',
    notificationsStatusDelivered: 'Livre',
    notificationsStatusFailed: 'Echoue',
    notificationsStatusUnknown: 'Inconnu',
    notificationsCountTitle: 'Notifications {label}',
    notificationsNoItems: 'Aucune notification a afficher.',
    notificationsUnreadTag: 'NON LUE',
    notificationsByActor: 'par {actor}',
    notificationsMarkRead: 'Marquer lue',
    notificationsFailedLoad: 'Echec du chargement des notifications.',
    notificationsMarkedRead: 'Marquee comme lue.',
    notificationsMarkReadFailed: 'Echec du marquage en lue.',
    notificationsMarkedAllRead: 'Toutes les notifications ont ete marquees lues.',
    notificationsMarkAllReadFailed: 'Echec du marquage global en lu.',
    notificationsArchive: 'Archiver',
    notificationsArchived: 'Notification archivee.',
    notificationsArchiveFailed: 'Echec de l\'archivage de la notification.',
    notificationsRestore: 'Restaurer',
    notificationsRestored: 'Notification restauree.',
    notificationsRestoreFailed: 'Echec de la restauration de la notification.',
    notificationsDelete: 'Supprimer',
    notificationsDeleted: 'Notification supprimee.',
    notificationsDeleteFailed: 'Echec de la suppression de la notification.',
    notificationsClearAll: 'Tout effacer',
    notificationsClearingAll: 'Effacement...',
    notificationsClearedAll: 'Toutes les notifications ont ete effacees.',
    notificationsClearAllFailed: 'Echec de l\'effacement des notifications.',
    notificationsClearAllConfirm: 'Effacer toutes les notifications visibles ? Elles seront deplacees vers supprimees.',
    
    // Dashboard
    welcomeBack: "Bon retour",
    dashboardOverview: "Voici un aperçu de l'analyse des procès-verbaux du conseil",
    totalMeetings: 'Réunions Totales',
    analyzedSegments: 'Segments Analysés',
    actionItems: 'Points d\'Action',
    themesTracked: 'Thèmes Suivis',
    themeDistribution: 'Distribution des Thèmes',
    sentimentAnalysis: 'Analyse des Sentiments',
    monthlyTrends: 'Tendances Mensuelles',
    recentActivity: 'Activité Récente',
    dashboardCreateEvent: 'Créer un Événement',
    
    // Settings
    managePreferences: 'Gérez vos préférences d\'application',
    appearance: 'Apparence',
    darkMode: 'Mode Sombre',
    switchTheme: 'Basculer entre le thème clair et sombre',
    language: 'Langue',
    notifications: 'Notifications',
    pushNotifications: 'Notifications Push',
    receiveNotifications: 'Recevoir des notifications dans l\'application',
    emailAlerts: 'Alertes Email',
    receiveEmail: 'Recevoir des emails pour les mises à jour importantes',
    systemTests: 'Tests Système',
    testFeatures: 'Testez les fonctionnalités intégrées',
    testModelEvaluation: 'Tester l\'Évaluation du Modèle',
    testAISummarization: 'Tester le Résumé IA',
    testSentimentAnalysis: 'Tester l\'Analyse des Sentiments',
    about: 'À Propos',
    version: 'Version',
    user: 'Utilisateur',
    role: 'Rôle',
    
    // Common
    loading: 'Chargement...',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    view: 'Voir',
    close: 'Fermer',
    submit: 'Soumettre',
    success: 'Succès',
    error: 'Erreur',
    warning: 'Avertissement',
    info: 'Information',
    yes: 'Oui',
    no: 'Non',
    searchPlaceholder: 'Rechercher...',
    noResults: 'Aucun résultat trouvé',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedSettings = localStorage.getItem('appSettings');
    if (savedSettings) {
      const parsed = JSON.parse(savedSettings);
      if (parsed.language) {
        setLanguage(parsed.language);
      }
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  const t = (key, params = {}) => {
    const template = translations[language]?.[key] || translations['en'][key] || key;
    return Object.keys(params).reduce((result, token) => {
      return result.replace(new RegExp(`\\{${token}\\}`, 'g'), String(params[token]));
    }, template);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;

